# DevOps Portfolio

This repository hosts my personal DevOps portfolio, showcasing:

- Linux server management
- AWS infrastructure & services
- CI/CD pipelines with GitLab & Docker
- Automated build processes

## Deployment

GitHub Actions will automatically deploy `index.html` to GitHub Pages on every push to `main`.

**Site URL:**  
`https://<your-username>.github.io/portfolio/`
